// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIckzUKhw2QQj4IztXOxSTaQMHHK9AHrI',
    appId: '1:35924330569:web:5b0ee4a7490ba11c771798',
    messagingSenderId: '35924330569',
    projectId: 'practise-project-52286',
    authDomain: 'practise-project-52286.firebaseapp.com',
    storageBucket: 'practise-project-52286.appspot.com',
    measurementId: 'G-KDF8E8VC29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWCPBtVfcrSB69s4kgvGH1eLT_QdYWyM8',
    appId: '1:35924330569:android:423e80ed26813c3b771798',
    messagingSenderId: '35924330569',
    projectId: 'practise-project-52286',
    storageBucket: 'practise-project-52286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFzSzkwfXpCS8nURjKZL0f8Mgd3RjKj4w',
    appId: '1:35924330569:ios:03910d035c9841d4771798',
    messagingSenderId: '35924330569',
    projectId: 'practise-project-52286',
    storageBucket: 'practise-project-52286.appspot.com',
    iosBundleId: 'com.example.footwearAdmin',
  );

}